# -*- coding: utf-8 -*-
"""llmeval.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12ZI6yvgdCuUvjAK22OiOrPHnApPEAy2Y
"""

pip install groq

from groq import Groq
client=Groq(api_key="")

response=client.chat.completions.create(model="llama-3.1-8b-instant",messages=[{"role":"system", "content" :"you are helpful assistant"},{"role":"user","content":"dr mgr university "}])



print(response.choices[0].message.content)

client= Groq(api_key="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")

query="I have been charged twice for my order no 12345 and no one is responding to my mails"

response=client.chat.completions.create(model="llama-3.1-8b-instant",messages=[{"role":"system","content":"you re a customer support classifier"},{"role":"user","content":f"Is this complaint urgent or not? Please reply with just urgent or not urgent {query}"}])

print(response.choices[0].message.content)

testcases=[{'content':'account got hacked','expected':'urgent'},{'content':'I was charged twice for my order #12345','expected':'urgent'},{'content':'I need to change my email','expected':'not_urgent'},{'content':'I want to know your timings','expected':'not_urgent'},{'content':'my order was delayed by 3 weeks','expected':'urgent'}]

import time
c=0
for test in testcases:
  time.sleep(5)
  response=client.chat.completions.create(model="llama-3.1-8b-instant",messages=[{"role":"system","content":"you are a customer support classifier"},{"role":"user","content":f"classify the customer response as urgent or not_urgent,you must respond with only one word urgent or not_urgent,nothing else {test['content']}"}])
  print(response.choices[0].message.content.lower())
  if response.choices[0].message.content.lower() == test['expected']:
      c=c+1
print (c)
eval=c/len(testcases)
print(eval)

The reason why '3' was displayed as the value of `c` (the number of correct classifications) is due to two main factors related to how the `if` condition was evaluated:

1.  **Exact Match Requirement**: The condition `if response.choices[0].message.content == test['expected']:` performs a **case-sensitive comparison** and requires an **exact string match**. While the line `print(response.choices[0].message.content.lower())` prints the lowercased version of the model's response, the comparison for incrementing `c` uses the raw, un-lowercased response.

2.  **Model Responses that Did Not Exactly Match**:
    *   For the test case: `{'content':'I want to know your timings','expected':'not urgent'}`, the model's response was a conversational message (`i'll provide the classification...`) instead of the expected 'not urgent'. This caused the `if` condition to be false, and `c` was not incremented.
    *   For another test case (most likely `{'content':'my order was delayed by 3 weeks','expected':'urgent'}`), even though its lowercased output was `urgent`, the model's *original* response string was probably not *exactly* `'urgent'` (e.g., it might have been `'Urgent'`, `'urgent.'`, or included extra characters). Because of the case-sensitive exact match requirement, this also resulted in the `if` condition being false, and `c` was not incremented for this case.

Therefore, only 3 of the 5 test cases resulted in an exact, case-sensitive match between the model's raw response and the `test['expected']` value, leading to `c` being 3.