# -*- coding: utf-8 -*-
"""llmeval_from files.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18GJqeHwzO8tqBWONvjbp_ACfjrhBpwQG
"""

import json
import time

complaints=[{"id":1,"complaint":"I was charged twice for order #123"},{"id":2,"complaint":"can you tell me your office hours"},{"id":3,"complaint":"My account has been hacked, please help"},{"id":4,"complaint":"I want to update my email address"},{"id":5,"complaint":"I haven't recieved my order from 3 weeks ago."}]

with open("complaints.json", "w") as f:
  json.dump(complaints,f)

pip install groq

from groq import Groq

client=Groq(api_key="gsk_YMyCA5P6PoBh9nrvzN13WGdyb3FYxU5HOqeUieaPKrtGLHVr2W8")

results=[]
with open ("complaints.json","r") as f:
  complaints=json.load(f)
for i in complaints:
  response=client.chat.completions.create(model='llama-3.1-8b-instant',messages=[{"role":"system","content":"you are a customer support classifier assistant"},{"role":"user","content":f"classify the customer response as urgent or not_urgent,you are not supposed to give any conversational response , just you must respond with only one word urgent or not_urgent,nothing else{i['complaint']}"}])
  result= response.choices[0].message.content.lower()
  if result=="urgent":
    classification="urgent"
  elif result=="not_urgent":
    classification="not_urgent"
  else:
    classification="unknown"
  results.append({"id":i["id"],"complaint":i["complaint"],"classification":classification})

print(results)

with open("results.json","w") as f:
  json.dump(results,f)